baseURL: 'https://du4ng.github.io/' # ƒë·ªïi gi·ªëng domain c·ªßa host
title: bbtd
# paginate: 5
# S·ªë b√†i vi·∫øt tr√™n m·ªói trang
pagination:
  pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: G-F9VS7QYQ27

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Dung
  description: 'Yikes!'
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ['Me', 'You'] # multiple authors
  images: ['<link or path of image for opengraph, twitter-cards>']
  DateFormat: 'January 2, 2006'
  defaultTheme: auto # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false


  static:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: favicon.ico
    favicon16x16: favicon.ico
    favicon32x32: favicon.ico
    apple_touch_icon: favicon.ico
    safari_pinned_tab: favicon.ico

  label:
    text: Dung
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: 'This is subtitle'
    imageUrl: '<img location>'
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: 
      p áqq


      bbtd

    Content: 
      Ch√∫t x√†m x√≠ v·ªÅ **software**,
      

      v√† m·ªôt ch√∫t ngo√†i l·ªÅ.üê¶‚Äç‚¨õ #üëΩüé≤

  socialIcons:
    # - name: stackoverflow
    #   url: 
    # - name: dev 
    #   url: 
    - name: github
      url: https://github.com/Du4nG
    - name: linkedin
      url: https://www.linkedin.com/in/bbtd/



  analytics:
    google:
      SiteVerificationTag: 'XYZabc'
    bing:
      SiteVerificationTag: 'XYZabc'
    yandex:
      SiteVerificationTag: 'XYZabc'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: https://ctftime.org
    Text: 'Suggest Changes' # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']
menu:
  main:
    # - identifier: categories
    #   name: B√†i vi·∫øt
    #   url: /categories/
    #   weight: 1
    - identifier: tags
      name: Tags
      url: /tags
      weight: 2
    - identifier: example
      name: Vault
      url: https://beacons.ai/livin/room
      weight: 3
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai